# Generated by Django 4.2.26 on 2026-01-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("senha", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Barbeiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="media/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "barbeiro",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Folga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                ("motivo", models.CharField(blank=True, max_length=100)),
                (
                    "barbeiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.barbeiro"
                    ),
                ),
            ],
            options={
                "db_table": "folgas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "intervalo",
                    models.PositiveIntegerField(
                        help_text="Intervalo entre horários (em minutos)"
                    ),
                ),
                ("almoco_inicio", models.TimeField(blank=True, null=True)),
                ("almoco_fim", models.TimeField(blank=True, null=True)),
                (
                    "barbeiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.barbeiro"
                    ),
                ),
            ],
            options={
                "db_table": "expediente",
                "managed": True,
                "unique_together": {("barbeiro", "dia_semana")},
            },
        ),
    ]
