# Generated by Django 4.2.26 on 2026-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barbeiro",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="barbeiros/"),
        ),
    ]
