# Generated by Django 4.2.26 on 2025-12-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("servico", models.CharField(max_length=100)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "agendamentos",
                "managed": True,
            },
        ),
    ]
