# Generated by Django 4.2.26 on 2025-12-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentos",
            name="valor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
