# Generated by Django 4.2.26 on 2026-01-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
        ("agendamento", "0003_agendamentos_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentos",
            name="barbeiro",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.barbeiro",
            ),
            preserve_default=False,
        ),
    ]
