# Generated by Django 4.2.26 on 2026-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0004_agendamentos_barbeiro"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agendamentos",
            constraint=models.UniqueConstraint(
                fields=("barbeiro", "data"), name="unique_horario_barbeiro"
            ),
        ),
    ]
